import type { Metadata } from "next";
import "@copilotkit/react-core/v2/styles.css";
import "./globals.css";
import { AuthProvider } from "@/app/components/AuthProvider";
import { CopilotProvider } from "@/app/components/CopilotProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full">
        <AuthProvider>
          <CopilotProvider>{children}</CopilotProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
