import type { Metadata } from "next";
import { CopilotKit } from "@copilotkit/react-core/v2"; 
import "@copilotkit/react-core/v2/styles.css"; 
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // TODO: Implement optional signin feature. Split CopilotKit to component to avoid re-render layout
  const userToken = "Bearer <auth access token>";

  return (
    <html lang="en" className="h-full">
      <body className="h-full">
        <CopilotKit
          runtimeUrl="/api/copilotkit"
          properties={{
            Authorization: userToken,
          }}
        >
          {children}
        </CopilotKit>
      </body>
    </html>
  );
}
